apiVersion: v1
clusters:
- cluster:
    api-version: v1
    server: https://master.rhsademo.net:443
  name: master-rhsademo-net:443
contexts:
- context:
    cluster: master-rhsademo-net:443
    namespace: mepley-test
    user: mepley/master-rhsademo-net:443
  name: mepley-test/master-rhsademo-net:443/mepley
current-context: mepley-test/master-rhsademo-net:443/mepley
users:
- name: mepley/master-rhsademo-net:443
  user:
    token: XpQ5ywvcG-YEavIzD1YgnxYb4sE4oyfnKRETz-YKtbw
